logdir: /logdir/atari_pong/dreamerv2/1
seed: 0
task: atari_ms_pacman
envs: 1
envs_parallel: none
render_size:
- 128
- 128
process_size:
- 64
- 64
use_obj_detection: true
obj_detection_threshold: 0.7
dmc_camera: -1
atari_grayscale: true
time_limit: 100
action_repeat: 4
steps: 500000
log_every: 300.0
eval_every: 300.0
eval_eps: 1
prefill: 100
pretrain: 1
train_every: 16
train_steps: 5
expl_until: 0
replay:
  capacity: 10000.0
  ongoing: false
  minlen: 50
  maxlen: 50
  prioritize_ends: true
dataset:
  batch: 8
  length: 20
log_keys_video:
- image
log_keys_sum: ^$
log_keys_mean: ^$
log_keys_max: ^$
precision: 16
jit: true
debug_prints: true
clip_rewards: tanh
expl_behavior: greedy
expl_noise: 0.0
eval_noise: 0.0
eval_state_mean: false
grad_heads:
- decoder
- reward
- discount
pred_discount: true
rssm:
  ensemble: 1
  hidden: 2
  deter: 2
  stoch: 8
  discrete: 8
  act: elu
  norm: none
  std_act: sigmoid2
  min_std: 0.1
encoder:
  mlp_keys: $^
  cnn_keys: image
  act: elu
  norm: none
  cnn_depth: 2
  cnn_kernels:
  - 4
  - 4
  - 4
  - 4
  mlp_layers:
  - 5
  - 5
decoder:
  mlp_keys: $^
  cnn_keys: image
  act: elu
  norm: none
  cnn_depth: 2
  cnn_kernels:
  - 5
  - 5
  - 6
  - 6
  mlp_layers:
  - 5
  - 5
reward_head:
  layers: 2
  units: 10
  act: elu
  norm: none
  dist: mse
discount_head:
  layers: 2
  units: 10
  act: elu
  norm: none
  dist: binary
loss_scales:
  kl: 0.1
  reward: 1.0
  discount: 5.0
  proprio: 1.0
kl:
  free: 0.0
  forward: false
  balance: 0.8
  free_avg: true
model_opt:
  opt: adam
  lr: 0.0002
  eps: 1e-05
  clip: 100
  wd: 1e-06
actor:
  layers: 1
  units: 4
  act: elu
  norm: none
  dist: auto
  min_std: 0.1
critic:
  layers: 1
  units: 4
  act: elu
  norm: none
  dist: mse
actor_opt:
  opt: adam
  lr: 4e-05
  eps: 1e-05
  clip: 100
  wd: 1e-06
critic_opt:
  opt: adam
  lr: 0.0001
  eps: 1e-05
  clip: 100
  wd: 1e-06
discount: 0.999
discount_lambda: 0.95
imag_horizon: 5
actor_grad: auto
actor_grad_mix: 0.1
actor_ent: 0.001
slow_target: true
slow_target_update: 100
slow_target_fraction: 1
slow_baseline: true
reward_norm:
  momentum: 1.0
  scale: 1.0
  eps: 1e-08
expl_intr_scale: 1.0
expl_extr_scale: 0.0
expl_opt:
  opt: adam
  lr: 0.0003
  eps: 1e-05
  clip: 100
  wd: 1e-06
expl_head:
  layers: 1
  units: 4
  act: elu
  norm: none
  dist: mse
expl_reward_norm:
  momentum: 1.0
  scale: 1.0
  eps: 1e-08
disag_target: stoch
disag_log: false
disag_models: 10
disag_offset: 1
disag_action_cond: true
expl_model_loss: kl
